name: skogestad
channels:
 - conda-forge
 - defaults
dependencies:
 - future
 - matplotlib<=2.2.2
 - scipy>=1.0.0
 - numpy>=1.14.0
 - sympy>=1.2
 - mock
 - numpydoc
 - nose
 - slycot
 - control
 - python-coveralls
 - nose-cov
 - pytest
 - nbformat
 - nbconvert
 - pip:
    - harold>=1.0.1
